// <auto-generated />
using System;
using LearningNotificationHubs.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearningNotificationHubs.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.7.21378.4");

            modelBuilder.Entity("LearningNotificationHubs.API.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PnsToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "Username");

                    b.HasIndex("Username");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("LearningNotificationHubs.API.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LearningNotificationHubs.API.Models.Device", b =>
                {
                    b.HasOne("LearningNotificationHubs.API.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningNotificationHubs.API.Models.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
